#!/bin/bash

## -F, --flush [chain]
## Clear all rules
sudo iptables -F

# set defaults rules
sudo iptables --policy INPUT DROP
sudo iptables --policy FORWARD ACCEPT
sudo iptables --policy OUTPUT DROP

# for management - ssh
sudo iptables --append INPUT --in-interface enp0s3 --protocol tcp --destination-port 4422 --match state --state NEW,ESTABLISHED --jump ACCEPT
sudo iptables --append OUTPUT --out-interface enp0s3 --protocol tcp --source-port 4422 --match state --state ESTABLISHED --jump ACCEPT

# Allow DNS
sudo iptables -A OUTPUT --out-interface enp0s3 -p udp --dport 53 -j ACCEPT

# Allows synchronized time (ntpdate)
sudo iptables -A OUTPUT --out-interface enp0s3 -p udp --dport 123 -j ACCEPT

# for time-server
sudo iptables -A INPUT --in-interface enp0s8 -p udp --dport 123 -j ACCEPT
sudo iptables -A OUTPUT --out-interface enp0s8 -p udp --dport 123 -j ACCEPT
sudo iptables -A INPUT --in-interface enp0s9 -p udp --dport 123 -j ACCEPT
sudo iptables -A OUTPUT --out-interface enp0s9 -p udp --dport 123 -j ACCEPT

# Now, allow connection to website serverfault.com on port 80
sudo iptables --append OUTPUT --out-interface enp0s3 --protocol tcp --dport 80 -j ACCEPT
sudo iptables --append OUTPUT --out-interface enp0s3 --protocol tcp --dport 443 -j ACCEPT
sudo iptables --append INPUT --in-interface enp0s3 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# Allow Ping
sudo iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
sudo iptables -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT

sudo iptables -A OUTPUT -p icmp --icmp-type echo-request -j ACCEPT
sudo iptables -A OUTPUT -p icmp --icmp-type echo-reply -j ACCEPT

